baseURL = 'https://hosting-netlify.netlify.app/'
locale  = 'en-US'
title   = 'Hosting Test - Netlify'

enableGitInfo = true

[caches]
  _merge = 'deep'

[cascade]
  _merge = 'deep'

[markup]
  _merge = 'deep'

[security]
  _merge = 'deep'

[[module.imports]]
  path = 'github.com/jmooring/hugo-module-feature-test'

[[module.imports]]
  path = 'hugo-theme-example'
