[build]
command = """\
  npm install "sass-embedded@${DART_SASS_VERSION}" && \
  path_nm=/opt/build/repo/node_modules && \
  path_dse=sass-embedded-linux-x64/dart-sass-embedded/dart-sass-embedded && \
  cp "${path_nm}/${path_dse}" "${path_nm}/.bin" && \
  hugo --gc --minify
  """
publish = "public"

[build.environment]
DART_SASS_VERSION = "1.56.2"
HUGO_VERSION = "0.108.0"
TZ = "America/Los_Angeles"
